//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNhom
    {
        public int MaThongTinNhom { get; set; }
        public string TenTaiKhoan { get; set; }
        public Nullable<int> MaNhom { get; set; }
    
        public virtual Nhom Nhom { get; set; }
    }
}
